name: test workflow

on: push

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: test job
        run: echo "this is first workflow"
  second-test-job:
    runs-on: windows-latest
    needs: test-job
    steps:
      - name: 2nd test
        run: echo "this is 2nd test workflow"
    
